# Generated by Django 4.0.3 on 2022-04-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
        migrations.AddField(
            model_name='text',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
        migrations.AddField(
            model_name='video',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Счетчик просмотров'),
        ),
    ]
